#!/usr/bin/python3
from os import makedirs
import sys


args = sys.argv
if len(args) < 2:
    print("No args given.")
    exit(-1)
for arg in args[1:]:
    # mkdir(arg)
    for time in ["January", "Feburary", "December", "OpenContest"]:
        # mkdir(f"{arg}/{time}")
        for rank in ["Bronze", "Silver", "Gold", "Platinum"]:
            makedirs(f"USACO/{arg}/{time}/{rank}")